// <auto-generated />
namespace Messenger.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class chnagedatetimetosendtime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chnagedatetimetosendtime));
        
        string IMigrationMetadata.Id
        {
            get { return "201812191448582_chnage datetime to sendtime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
